name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get short Git SHA for tagging
        id: get_sha
        run: echo "SHA_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            tarkant/dl-api:latest # Always tag with 'latest'
            tarkant/dl-api:${{ steps.get_sha.outputs.SHA_SHORT }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
